# Generated by Django 4.2.16 on 2024-11-05 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionCatalog",
            fields=[
                ("catalog_id", models.AutoField(primary_key=True, serialize=False)),
                ("direction_id", models.IntegerField(verbose_name="研究方向编号")),
                ("total_quota", models.IntegerField(verbose_name="年度招生指标")),
                ("additional_quota", models.IntegerField(verbose_name="补充招生指标")),
                ("year", models.IntegerField(verbose_name="招生年度")),
            ],
        ),
        migrations.CreateModel(
            name="Applicant",
            fields=[
                ("applicant_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="考生姓名")),
                ("birth_date", models.DateField(verbose_name="考生出生日期")),
                (
                    "id_card_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="考生身份证号"
                    ),
                ),
                ("origin", models.CharField(max_length=255, verbose_name="考生生源地")),
                (
                    "undergraduate_major",
                    models.CharField(max_length=100, verbose_name="考生本科专业"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="考生邮箱")),
                ("phone", models.CharField(max_length=20, verbose_name="考生电话")),
                (
                    "undergraduate_school",
                    models.CharField(max_length=255, verbose_name="本科院校"),
                ),
                (
                    "school_type",
                    models.CharField(max_length=50, verbose_name="本科学校类型"),
                ),
                ("resume", models.TextField(blank=True, verbose_name="志愿选择")),
            ],
        ),
        migrations.CreateModel(
            name="Mentor",
            fields=[
                ("mentor_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="导师姓名")),
                ("title", models.CharField(max_length=100, verbose_name="导师职称")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photos/",
                        verbose_name="导师照片",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="导师简介")),
                ("email", models.EmailField(max_length=254, verbose_name="导师邮箱")),
                ("phone", models.CharField(max_length=20, verbose_name="导师电话")),
            ],
        ),
        migrations.CreateModel(
            name="SystemRole",
            fields=[
                ("role_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Student", "Student"),
                            ("Mentor", "Mentor"),
                            ("Admin", "Admin"),
                        ],
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("user_role_id", models.AutoField(primary_key=True, serialize=False)),
                ("object_id", models.PositiveIntegerField(default=0)),
                (
                    "content_type",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentor_student.systemrole",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemActivity",
            fields=[
                ("activity_id", models.AutoField(primary_key=True, serialize=False)),
                ("activity", models.TextField(verbose_name="核心业务需求活动描述")),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentor_student.systemrole",
                        verbose_name="角色ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("subject_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="学科名称")),
                ("level", models.CharField(max_length=50, verbose_name="学科等级")),
                ("description", models.TextField(blank=True, verbose_name="学科描述")),
                ("type", models.CharField(max_length=50, verbose_name="学科类型")),
                (
                    "parent_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mentor_student.subject",
                        verbose_name="上级学科ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MentorCatalogAssignment",
            fields=[
                ("assignment_id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField(verbose_name="分配年度")),
                (
                    "has_admission_eligibility",
                    models.BooleanField(default=False, verbose_name="是否具备招生资格"),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentor_student.admissioncatalog",
                        verbose_name="招生目录ID",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentor_student.mentor",
                        verbose_name="导师ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MentorApplicantPreference",
            fields=[
                ("preference_id", models.AutoField(primary_key=True, serialize=False)),
                ("preference_rank", models.IntegerField(verbose_name="志愿优先级")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "待定"),
                            ("Accepted", "已接受"),
                            ("Rejected", "已拒绝"),
                        ],
                        default="Pending",
                        max_length=20,
                        verbose_name="志愿状态",
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="备注信息")),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentor_student.applicant",
                        verbose_name="考生ID",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentor_student.mentor",
                        verbose_name="导师ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mentor",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mentor_student.subject",
                verbose_name="学科ID",
            ),
        ),
        migrations.CreateModel(
            name="ApplicantScore",
            fields=[
                ("score_id", models.AutoField(primary_key=True, serialize=False)),
                ("preliminary_score", models.FloatField(verbose_name="初试成绩")),
                ("final_score", models.FloatField(verbose_name="复试成绩")),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentor_student.applicant",
                        verbose_name="考生ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="admissioncatalog",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mentor_student.subject",
                verbose_name="学科ID",
            ),
        ),
    ]
