# Generated by Django 4.2.16 on 2024-11-08 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='subject',
        ),
        migrations.AddField(
            model_name='mentor',
            name='id_card_number',
            field=models.CharField(default=0, max_length=20, unique=True, verbose_name='导师身份证号'),
        ),
        migrations.CreateModel(
            name='MentorSubjectDirection',
            fields=[
                ('direction_id', models.AutoField(primary_key=True, serialize=False)),
                ('research_direction', models.CharField(max_length=255, verbose_name='研究方向')),
                ('year', models.IntegerField(verbose_name='招生年度')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor_student.mentor', verbose_name='导师ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor_student.subject', verbose_name='学科ID')),
            ],
            options={
                'verbose_name': '导师招生方向',
                'verbose_name_plural': '导师招生方向',
                'unique_together': {('mentor', 'subject', 'research_direction', 'year')},
            },
        ),
    ]
