# Generated by Django 4.2.16 on 2024-11-05 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mentor_student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="user_id",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="mentor",
            name="user_id",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name="systemrole",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="systemrole",
            name="name",
            field=models.CharField(
                choices=[
                    ("Student", "Student"),
                    ("Mentor", "Mentor"),
                    ("Admin", "Admin"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mentor_student.systemrole",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="user_id",
            field=models.IntegerField(),
        ),
    ]
