# Generated by Django 4.2.16 on 2024-11-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_student', '0002_mentor_id_card_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='id_card_number',
            new_name='Sid_card_number',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='id_card_number',
            new_name='Mid_card_number',
        ),
    ]
