# Generated by Django 4.2.16 on 2024-11-05 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mentor_student", "0002_applicant_user_id_mentor_user_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicant",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="mentor",
            name="user_id",
        ),
    ]
