# Generated by Django 4.2.16 on 2024-11-08 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mentor_student', '0002_remove_mentor_photo_remove_mentor_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicantscore',
            options={'verbose_name': '考生成绩', 'verbose_name_plural': '考生成绩'},
        ),
        migrations.AddField(
            model_name='applicantscore',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentor_student.subject', verbose_name='报考学科'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='导师身份证号'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
