# Generated by Django 4.2.16 on 2024-11-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_student', '0003_rename_id_card_number_applicant_sid_card_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='Sid_card_number',
            new_name='id_card_number',
        ),
    ]
