# Generated by Django 4.2.16 on 2024-11-08 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_student', '0003_alter_applicantscore_options_applicantscore_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='parent_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_subjects', to='mentor_student.subject'),
        ),
    ]
