# Generated by Django 4.2.16 on 2024-11-08 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_student', '0004_alter_subject_parent_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissioncatalog',
            options={'verbose_name': '招生计划', 'verbose_name_plural': '招生计划'},
        ),
        migrations.AlterField(
            model_name='admissioncatalog',
            name='additional_quota',
            field=models.IntegerField(default=0, verbose_name='补充招生指标'),
        ),
        migrations.AlterField(
            model_name='admissioncatalog',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor_student.subject', verbose_name='学科'),
        ),
        migrations.AlterField(
            model_name='admissioncatalog',
            name='year',
            field=models.IntegerField(verbose_name='年度'),
        ),
        migrations.AlterUniqueTogether(
            name='admissioncatalog',
            unique_together={('subject', 'direction_id', 'year')},
        ),
    ]
